/**

  @file       watchdog.h
  @brief      External-watchdog kick task and the check-in registry that gates it.
  @details    The hardware block diagram is explicit that the WDT_WDI pulse train is generated by
              a *task*, not a timer: a timer keeps running while the CPU is wedged, whereas task
              switching requires a working CPU, so a task-driven kick proves something a
              timer-driven one does not.

              This header takes that one step further. A lone kicker task proves only that *it*
              is being scheduled — a sensor task stuck forever on a wedged I2C bus would never
              stop the pulses. So the kick is gated on check-ins: every flight task calls
              CheckIn() once per loop, and the watchdog task pulses WDT_WDI only when every
              registered client has checked in within its own deadline. When one has not, the
              pulses stop and the external circuit resets the board — which is the whole point of
              having one.

              @par Deadlines
              Per-client, derived in config.h from the period of the task they police. A boot
              grace period covers the interval between the scheduler starting and each task
              reaching its first check-in.

              @par Threading
              CheckIn() is a single aligned 32-bit store, so it is safe to call from any task
              without a lock and cheap enough to sit in a hot loop. It is not ISR-safe only
              because nothing needs it to be.

  @author     Viola Case
  @date       29.08.2026
  @copyright  © Viola Case, 2026. All rights reserved.

**/
#pragma once

#include <cstdint>

namespace OwlSat::Watchdog {

  /// Tasks whose liveness gates the pulse train. Order indexes the deadline table.
  enum class Client : uint8_t {
    Sensor   = 0,
    Link     = 1,
    Transmit = 2,
    Count    = 3,
  };

  /**
   * @brief Zeroes the registry and starts the boot grace period.
   *
   * Call before the scheduler starts. Does not touch the WDT_WDI line — that is
   * Hal::WatchdogInit()'s job, and the task's first act.
   */
  void Init();

  /**
   * @brief Records that @p client is still making progress.
   *
   * Called once per iteration of each monitored task's loop, at the top, after whatever blocking
   * call paces it has returned. Calling it at the bottom of the loop instead would mean a task
   * that blocks forever mid-iteration still counts as live until its deadline, which is the same
   * answer but a loop later.
   */
  void CheckIn(Client client);

  /**
   * @brief Takes a client out of the registry, so its silence no longer stops the pulses.
   *
   * For a subsystem deliberately shut down — the radio powered off to save budget, say. A task
   * that is *supposed* to be gone must not reset the spacecraft.
   */
  void Suspend(Client client);

  /// Puts a suspended client back in the registry, with its deadline reset from now.
  void Resume(Client client);

  /**
   * @brief The kick task. Never returns.
   *
   * Pulses WDT_WDI every OWLSAT_WATCHDOG_PERIOD_MS for as long as every registered client is
   * inside its deadline. On the first late client it stops pulsing, reports which one and by how
   * much, and keeps checking — if the client recovers before the external part times out, the
   * pulse train resumes and no reset happens.
   *
   * @param params Unused (pass nullptr).
   */
  void WatchdogTask(void *params);

} // namespace OwlSat::Watchdog
